alias: 'Start or Stop HomeKit'
trigger:
  - platform: state
    entity_id: input_boolean.instance_hubs_connected
  - platform: state
    entity_id: input_boolean.instance_media_connected
  - platform: state
    entity_id: input_boolean.instance_trackers_connected
  - platform: state
    entity_id: input_boolean.instance_zwave_connected
condition:
  condition: and
  conditions:
    - entity_id: input_boolean.instance_hubs_connected
      state: 'on'
    - entity_id: input_boolean.instance_media_connected
      state: 'on'
    - entity_id: input_boolean.instance_trackers_connected
      state: 'on'
    - entity_id: input_boolean.instance_zwave_connected
      state: 'on'
action:
  - service: homekit.start